### ISSUE TITLE
Mouse 2 хэлний сонголтгүй болгох

### ISSUE THREAD

**Issue by myagmarsurensedjav** [ganzorig-ganbat/bolor-tolidogch#3]
Mouse 2 дараад гарч ирж байгаа цэснээс дахиад хэлний сонголт хийх нь төвөгтэй юм аа. 

Буруу хэл алдаад сонгочихвол бүр баларна гарч ирсэн window оо хаагаад дахиад хайх хэрэгтэй болно. 

Шууд storage д хадгалсан lang аа ашиглачихвал зүгээр юм биш үү. Нэг дараад л үр дүн гарна.

**Comment by swganzo** [comment]
1. Window-өө хаах ямар ч шаардлага байхгүй. Дахиад хэлээ сонгоход л хангалттай.
2. Харин шууд storage-д хадгалсан lang-аа "bolor toli-дох" гэдэг parent context menu дээр дарахад гарч ирдэг байдлаар хийж болох юм.

**Comment by selmonal** [comment]
👍
